backend:
  name: git-gateway
  branch: main

# Add the route to your images, so Netlify CMS knows where to save uploads to.
media_folder: "src/static/img"
public_folder: "/static/img"

# When you want to use Netlify CMS:
# Run your Eleventy serve commands: `npm run start`
# In another terminal window, simultaneously run: "npx netlify-cms-proxy-server" for local backend
local_backend: true

# Add your collections. Here's an example of multiple collections:
collections:
  # First Collection
  - label: "Pages"
    name: "pages"
    extension: "json"
    files:
      - label: "Press"
        name: "press"
        file: "src/_data/people.json"
        fields:
          - { label: Name, name: name, widget: string }
    # create: true # This allows you to create new instances in the CMS
    editor:
      preview: false
